package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/beevik/etree"
)

type complexTypeInfo struct {
	attrs map[string]string
	base  string
	doc   string
}

type elementInfo struct {
	doc         string
	typeNames   []string
	inlineTypes []complexTypeInfo
}

func main() {
	// Run from repo root: go run ./cmd/vastdocgen -schema schemas/vast_4.2.xsd -out validator/vast42_docs_gen.go
	schemaPath := flag.String("schema", "schemas/vast_4.2.xsd", "path to VAST 4.2 schema")
	outPath := flag.String("out", "validator/vast42_docs_gen.go", "output file for generated docs")
	flag.Parse()

	data, err := generate(*schemaPath)
	if err != nil {
		log.Fatalf("doc generation failed: %v", err)
	}
	if err := os.WriteFile(*outPath, data, 0o644); err != nil {
		log.Fatalf("writing output failed: %v", err)
	}
}

func generate(schemaPath string) ([]byte, error) {
	doc := etree.NewDocument()
	if err := doc.ReadFromFile(schemaPath); err != nil {
		return nil, fmt.Errorf("read schema: %w", err)
	}
	root := doc.Root()
	if root == nil {
		return nil, fmt.Errorf("schema missing root element")
	}

	complexTypes := map[string]complexTypeInfo{}
	for _, child := range root.ChildElements() {
		if child.Tag == "complexType" {
			name := child.SelectAttrValue("name", "")
			if name == "" {
				continue
			}
			complexTypes[name] = parseComplexType(child)
		}
	}

	elements := map[string]*elementInfo{}
	collectElements(root, elements)

	nodeDocs := map[string]string{}
	attrDocs := map[string]map[string]string{}
	memo := map[string]map[string]string{}

	for name, info := range elements {
		desc := strings.TrimSpace(info.doc)
		if desc == "" && len(info.inlineTypes) > 0 {
			desc = strings.TrimSpace(info.inlineTypes[0].doc)
		}
		if desc == "" {
			for _, typeName := range info.typeNames {
				desc = typeDoc(typeName, complexTypes)
				if desc != "" {
					break
				}
			}
		}
		if desc != "" {
			nodeDocs[name] = desc
		}
		resolved := map[string]string{}
		for _, typeName := range info.typeNames {
			mergeAttrs(resolved, resolveTypeAttrs(typeName, complexTypes, memo))
		}
		for i := range info.inlineTypes {
			mergeAttrs(resolved, resolveInlineAttrs(&info.inlineTypes[i], complexTypes, memo))
		}
		if len(resolved) > 0 {
			attrDocs[name] = resolved
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/vastdocgen. DO NOT EDIT.\n")
	buf.WriteString("package validator\n\n")

	writeMap(&buf, "var vast42ElementDocs = map[string]string{", nodeDocs)
	writeNestedMap(&buf, "var vast42AttributeDocs = map[string]map[string]string{", attrDocs)
	return buf.Bytes(), nil
}

func parseComplexType(el *etree.Element) complexTypeInfo {
	info := complexTypeInfo{
		attrs: map[string]string{},
		base:  findBase(el),
		doc:   docText(el),
	}
	collectAttrDocs(el, info.attrs)
	return info
}

func findBase(el *etree.Element) string {
	if ext := el.FindElement("complexContent/extension"); ext != nil {
		return stripPrefix(ext.SelectAttrValue("base", ""))
	}
	if ext := el.FindElement("simpleContent/extension"); ext != nil {
		return stripPrefix(ext.SelectAttrValue("base", ""))
	}
	return ""
}

func collectAttrDocs(node *etree.Element, attrs map[string]string) {
	for _, child := range node.ChildElements() {
		switch child.Tag {
		case "annotation":
			continue
		case "element":
			continue
		case "attribute":
			name := child.SelectAttrValue("name", "")
			if name == "" {
				continue
			}
			doc := strings.TrimSpace(docText(child))
			if doc != "" {
				attrs[name] = doc
			}
		default:
			collectAttrDocs(child, attrs)
		}
	}
}

func collectElements(node *etree.Element, out map[string]*elementInfo) {
	for _, child := range node.ChildElements() {
		if child.Tag == "element" {
			name := child.SelectAttrValue("name", "")
			if name != "" {
				info := out[name]
				if info == nil {
					info = &elementInfo{typeNames: []string{}}
					out[name] = info
				}
				doc := docText(child)
				if info.doc == "" && doc != "" {
					info.doc = doc
				}
				typeName := stripPrefix(child.SelectAttrValue("type", ""))
				if typeName != "" && !contains(info.typeNames, typeName) {
					info.typeNames = append(info.typeNames, typeName)
				}
				if ct := child.FindElement("complexType"); ct != nil {
					parsed := parseComplexType(ct)
					info.inlineTypes = append(info.inlineTypes, parsed)
				}
			}
			collectElements(child, out)
			continue
		}
		collectElements(child, out)
	}
}

func contains(list []string, needle string) bool {
	for _, value := range list {
		if value == needle {
			return true
		}
	}
	return false
}

func docText(el *etree.Element) string {
	ann := el.FindElement("annotation")
	if ann == nil {
		return ""
	}
	docs := ann.FindElements("documentation")
	if len(docs) == 0 {
		return ""
	}
	parts := make([]string, 0, len(docs))
	for _, d := range docs {
		text := strings.TrimSpace(d.Text())
		if text != "" {
			parts = append(parts, text)
		}
	}
	return strings.Join(parts, "\n\n")
}

func stripPrefix(name string) string {
	if idx := strings.Index(name, ":"); idx >= 0 {
		return name[idx+1:]
	}
	return name
}

func typeDoc(name string, types map[string]complexTypeInfo) string {
	if name == "" {
		return ""
	}
	info, ok := types[stripPrefix(name)]
	if !ok {
		return ""
	}
	return strings.TrimSpace(info.doc)
}

func resolveTypeAttrs(name string, types map[string]complexTypeInfo, memo map[string]map[string]string) map[string]string {
	if name == "" {
		return nil
	}
	name = stripPrefix(name)
	if cached, ok := memo[name]; ok {
		return cached
	}
	info, ok := types[name]
	if !ok {
		memo[name] = nil
		return nil
	}
	attrs := cloneMap(info.attrs)
	if info.base != "" {
		mergeMissing(attrs, resolveTypeAttrs(info.base, types, memo))
	}
	memo[name] = attrs
	return attrs
}

func resolveInlineAttrs(info *complexTypeInfo, types map[string]complexTypeInfo, memo map[string]map[string]string) map[string]string {
	if info == nil {
		return nil
	}
	attrs := cloneMap(info.attrs)
	if info.base != "" {
		mergeMissing(attrs, resolveTypeAttrs(info.base, types, memo))
	}
	return attrs
}

func mergeAttrs(dst map[string]string, src map[string]string) {
	if len(src) == 0 {
		return
	}
	for k, v := range src {
		if v == "" {
			continue
		}
		dst[k] = v
	}
}

func mergeMissing(dst map[string]string, src map[string]string) {
	if len(src) == 0 {
		return
	}
	for k, v := range src {
		if v == "" {
			continue
		}
		if _, exists := dst[k]; !exists {
			dst[k] = v
		}
	}
}

func cloneMap(src map[string]string) map[string]string {
	cloned := make(map[string]string, len(src))
	for k, v := range src {
		if v == "" {
			continue
		}
		cloned[k] = v
	}
	return cloned
}

func writeMap(buf *bytes.Buffer, prefix string, data map[string]string) {
	buf.WriteString(prefix)
	buf.WriteString("\n")
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(buf, "\t%q: %q,\n", k, data[k])
	}
	buf.WriteString("}\n\n")
}

func writeNestedMap(buf *bytes.Buffer, prefix string, data map[string]map[string]string) {
	buf.WriteString(prefix)
	buf.WriteString("\n")
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		buf.WriteString("\t" + strconv.Quote(k) + ": {\n")
		inner := data[k]
		innerKeys := make([]string, 0, len(inner))
		for innerKey := range inner {
			innerKeys = append(innerKeys, innerKey)
		}
		sort.Strings(innerKeys)
		for _, innerKey := range innerKeys {
			fmt.Fprintf(buf, "\t\t%q: %q,\n", innerKey, inner[innerKey])
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
}
