package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/beevik/etree"
)

type complexTypeInfo struct {
	attrs map[string]string
	base  string
	doc   string
}

type occurrenceInfo struct {
	doc   string
	attrs map[string]string
}

func main() {
	// Run from repo root: go run ./cmd/vastdocgen -schema schemas/vast_4.2.xsd -out validator/vast42_docs_gen.go
	schemaPath := flag.String("schema", "schemas/vast_4.2.xsd", "path to VAST 4.2 schema")
	outPath := flag.String("out", "validator/vast42_docs_gen.go", "output file for generated docs")
	flag.Parse()

	data, err := generate(*schemaPath)
	if err != nil {
		log.Fatalf("doc generation failed: %v", err)
	}
	if err := os.WriteFile(*outPath, data, 0o644); err != nil {
		log.Fatalf("writing output failed: %v", err)
	}
}

func generate(schemaPath string) ([]byte, error) {
	doc := etree.NewDocument()
	if err := doc.ReadFromFile(schemaPath); err != nil {
		return nil, fmt.Errorf("read schema: %w", err)
	}
	root := doc.Root()
	if root == nil {
		return nil, fmt.Errorf("schema missing root element")
	}

	complexTypes := map[string]complexTypeInfo{}
	complexTypeElements := map[string]*etree.Element{}
	for _, child := range root.ChildElements() {
		if child.Tag == "complexType" {
			name := child.SelectAttrValue("name", "")
			if name == "" {
				continue
			}
			complexTypes[name] = parseComplexType(child)
			complexTypeElements[name] = child
		}
	}

	occurrences := map[string]occurrenceInfo{}
	attrMemo := map[string]map[string]string{}
	for _, child := range root.ChildElements() {
		if child.Tag != "element" {
			continue
		}
		collectOccurrences(nil, child, occurrences, complexTypes, complexTypeElements, attrMemo, map[string]bool{})
	}

	contextNodeDocs := map[string]string{}
	contextAttrDocs := map[string]map[string]string{}
	for path, occurrence := range occurrences {
		nodeName := pathLeaf(path)
		doc := strings.TrimSpace(occurrence.doc)
		if doc == "" {
			doc = fmt.Sprintf("Defined in VAST 4.2 XSD element <%s>.", nodeName)
		}
		contextNodeDocs[path] = doc
		if len(occurrence.attrs) > 0 {
			contextAttrDocs[path] = cloneMap(occurrence.attrs)
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/vastdocgen. DO NOT EDIT.\n")
	buf.WriteString("package validator\n\n")

	writeMap(&buf, "var vast42ContextElementDocs = map[string]string{", contextNodeDocs)
	writeNestedMap(&buf, "var vast42AttributeDocs = map[string]map[string]string{", contextAttrDocs)
	return buf.Bytes(), nil
}

func collectOccurrences(path []string, el *etree.Element, out map[string]occurrenceInfo, complexTypes map[string]complexTypeInfo, complexTypeElements map[string]*etree.Element, attrMemo map[string]map[string]string, typeStack map[string]bool) {
	name := el.SelectAttrValue("name", "")
	if name == "" {
		return
	}
	currentPath := appendPath(path, name)
	pathKey := joinPath(currentPath)
	resolvedDoc := strings.TrimSpace(docText(el))
	inlineType := el.FindElement("complexType")
	typeName := stripPrefix(el.SelectAttrValue("type", ""))
	if resolvedDoc == "" && inlineType != nil {
		resolvedDoc = strings.TrimSpace(docText(inlineType))
	}
	if resolvedDoc == "" {
		resolvedDoc = typeDoc(typeName, complexTypes)
	}
	resolvedAttrs := map[string]string{}
	if typeName != "" {
		mergeAttrs(resolvedAttrs, resolveTypeAttrs(typeName, complexTypes, attrMemo))
	}
	if inlineType != nil {
		parsed := parseComplexType(inlineType)
		mergeAttrs(resolvedAttrs, resolveInlineAttrs(&parsed, complexTypes, attrMemo))
	}
	existing := out[pathKey]
	if strings.TrimSpace(existing.doc) == "" && resolvedDoc != "" {
		existing.doc = resolvedDoc
	}
	if existing.attrs == nil {
		existing.attrs = map[string]string{}
	}
	mergeAttrs(existing.attrs, resolvedAttrs)
	out[pathKey] = occurrenceInfo{doc: existing.doc, attrs: cloneMap(existing.attrs)}
	if inlineType != nil {
		collectOccurrencesFromType(currentPath, inlineType, out, complexTypes, complexTypeElements, attrMemo, typeStack)
		return
	}
	if typeName != "" {
		collectOccurrencesFromTypeName(currentPath, typeName, out, complexTypes, complexTypeElements, attrMemo, typeStack)
	}
}

func collectOccurrencesFromTypeName(path []string, typeName string, out map[string]occurrenceInfo, complexTypes map[string]complexTypeInfo, complexTypeElements map[string]*etree.Element, attrMemo map[string]map[string]string, typeStack map[string]bool) {
	resolved := stripPrefix(typeName)
	if resolved == "" || typeStack[resolved] {
		return
	}
	complexType := complexTypeElements[resolved]
	if complexType == nil {
		return
	}
	typeStack[resolved] = true
	defer delete(typeStack, resolved)
	collectOccurrencesFromType(path, complexType, out, complexTypes, complexTypeElements, attrMemo, typeStack)
}

func collectOccurrencesFromType(path []string, complexType *etree.Element, out map[string]occurrenceInfo, complexTypes map[string]complexTypeInfo, complexTypeElements map[string]*etree.Element, attrMemo map[string]map[string]string, typeStack map[string]bool) {
	if complexType == nil {
		return
	}
	if extension := complexType.FindElement("complexContent/extension"); extension != nil {
		collectOccurrencesFromTypeName(path, extension.SelectAttrValue("base", ""), out, complexTypes, complexTypeElements, attrMemo, typeStack)
		collectOccurrencesFromContainer(path, extension, out, complexTypes, complexTypeElements, attrMemo, typeStack)
		return
	}
	if extension := complexType.FindElement("simpleContent/extension"); extension != nil {
		collectOccurrencesFromTypeName(path, extension.SelectAttrValue("base", ""), out, complexTypes, complexTypeElements, attrMemo, typeStack)
		return
	}
	collectOccurrencesFromContainer(path, complexType, out, complexTypes, complexTypeElements, attrMemo, typeStack)
}

func collectOccurrencesFromContainer(path []string, container *etree.Element, out map[string]occurrenceInfo, complexTypes map[string]complexTypeInfo, complexTypeElements map[string]*etree.Element, attrMemo map[string]map[string]string, typeStack map[string]bool) {
	if container == nil {
		return
	}
	for _, child := range container.ChildElements() {
		switch child.Tag {
		case "sequence", "choice", "all", "group":
			collectOccurrencesFromContainer(path, child, out, complexTypes, complexTypeElements, attrMemo, typeStack)
		case "element":
			collectOccurrences(path, child, out, complexTypes, complexTypeElements, attrMemo, typeStack)
		}
	}
}

func parseComplexType(el *etree.Element) complexTypeInfo {
	info := complexTypeInfo{
		attrs: map[string]string{},
		base:  findBase(el),
		doc:   docText(el),
	}
	collectAttrDocs(el, info.attrs)
	return info
}

func findBase(el *etree.Element) string {
	if ext := el.FindElement("complexContent/extension"); ext != nil {
		return stripPrefix(ext.SelectAttrValue("base", ""))
	}
	if ext := el.FindElement("simpleContent/extension"); ext != nil {
		return stripPrefix(ext.SelectAttrValue("base", ""))
	}
	return ""
}

func collectAttrDocs(node *etree.Element, attrs map[string]string) {
	for _, child := range node.ChildElements() {
		switch child.Tag {
		case "annotation":
			continue
		case "element":
			continue
		case "attribute":
			name := child.SelectAttrValue("name", "")
			if name == "" {
				continue
			}
			doc := strings.TrimSpace(docText(child))
			if doc != "" {
				attrs[name] = doc
			}
		default:
			collectAttrDocs(child, attrs)
		}
	}
}

func appendPath(path []string, name string) []string {
	next := make([]string, len(path)+1)
	copy(next, path)
	next[len(path)] = name
	return next
}

func docText(el *etree.Element) string {
	ann := el.FindElement("annotation")
	if ann == nil {
		return ""
	}
	docs := ann.FindElements("documentation")
	if len(docs) == 0 {
		return ""
	}
	parts := make([]string, 0, len(docs))
	for _, d := range docs {
		text := normalizeDocText(d.Text())
		if text != "" {
			parts = append(parts, text)
		}
	}
	return normalizeDocText(strings.Join(parts, "\n\n"))
}

func normalizeDocText(text string) string {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" {
		return ""
	}
	replacer := strings.NewReplacer(
		"cooridinate", "coordinate",
		"At lease", "At least",
		"should selected", "should be selected",
		"provied", "provided",
	)
	normalized := replacer.Replace(trimmed)
	return strings.Join(strings.Fields(normalized), " ")
}

func stripPrefix(name string) string {
	if idx := strings.Index(name, ":"); idx >= 0 {
		return name[idx+1:]
	}
	return name
}

func typeDoc(name string, types map[string]complexTypeInfo) string {
	if name == "" {
		return ""
	}
	info, ok := types[stripPrefix(name)]
	if !ok {
		return ""
	}
	return strings.TrimSpace(info.doc)
}

func joinPath(parts []string) string {
	return strings.Join(parts, ">")
}

func pathLeaf(path string) string {
	if idx := strings.LastIndex(path, ">"); idx >= 0 {
		return path[idx+1:]
	}
	return path
}

func attrsNeedContext(contextAttrs map[string]string, genericAttrs map[string]string) bool {
	if len(contextAttrs) == 0 {
		return false
	}
	if len(contextAttrs) != len(genericAttrs) {
		return true
	}
	for name, doc := range contextAttrs {
		if strings.TrimSpace(genericAttrs[name]) != strings.TrimSpace(doc) {
			return true
		}
	}
	return false
}

func resolveTypeAttrs(name string, types map[string]complexTypeInfo, memo map[string]map[string]string) map[string]string {
	if name == "" {
		return nil
	}
	name = stripPrefix(name)
	if cached, ok := memo[name]; ok {
		return cached
	}
	info, ok := types[name]
	if !ok {
		memo[name] = nil
		return nil
	}
	attrs := cloneMap(info.attrs)
	if info.base != "" {
		mergeMissing(attrs, resolveTypeAttrs(info.base, types, memo))
	}
	memo[name] = attrs
	return attrs
}

func resolveInlineAttrs(info *complexTypeInfo, types map[string]complexTypeInfo, memo map[string]map[string]string) map[string]string {
	if info == nil {
		return nil
	}
	attrs := cloneMap(info.attrs)
	if info.base != "" {
		mergeMissing(attrs, resolveTypeAttrs(info.base, types, memo))
	}
	return attrs
}

func mergeAttrs(dst map[string]string, src map[string]string) {
	if len(src) == 0 {
		return
	}
	for k, v := range src {
		if v == "" {
			continue
		}
		dst[k] = v
	}
}

func mergeMissing(dst map[string]string, src map[string]string) {
	if len(src) == 0 {
		return
	}
	for k, v := range src {
		if v == "" {
			continue
		}
		if _, exists := dst[k]; !exists {
			dst[k] = v
		}
	}
}

func cloneMap(src map[string]string) map[string]string {
	cloned := make(map[string]string, len(src))
	for k, v := range src {
		if v == "" {
			continue
		}
		cloned[k] = v
	}
	return cloned
}

func writeMap(buf *bytes.Buffer, prefix string, data map[string]string) {
	buf.WriteString(prefix)
	buf.WriteString("\n")
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(buf, "\t%q: %q,\n", k, data[k])
	}
	buf.WriteString("}\n\n")
}

func writeBoolMap(buf *bytes.Buffer, prefix string, data map[string]bool) {
	buf.WriteString(prefix)
	buf.WriteString("\n")
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(buf, "\t%q: %t,\n", k, data[k])
	}
	buf.WriteString("}\n\n")
}

func writeNestedMap(buf *bytes.Buffer, prefix string, data map[string]map[string]string) {
	buf.WriteString(prefix)
	buf.WriteString("\n")
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		buf.WriteString("\t" + strconv.Quote(k) + ": {\n")
		inner := data[k]
		innerKeys := make([]string, 0, len(inner))
		for innerKey := range inner {
			innerKeys = append(innerKeys, innerKey)
		}
		sort.Strings(innerKeys)
		for _, innerKey := range innerKeys {
			fmt.Fprintf(buf, "\t\t%q: %q,\n", innerKey, inner[innerKey])
		}
		buf.WriteString("\t},\n")
	}
	buf.WriteString("}\n")
}
